### ISSUE TITLE
Processed data from Spectacle available for download?

### ISSUE THREAD

**Issue by whtns** [drewvoigt10/cellcuratoR#6]
Hi, 

I'm very interested in your work with cellcurator and spectacle. I work with retinal scRNAseq data. Since the data is already processed for viewing in spectacle, is it possible to download from a webserver rather than working from the raw data from GEO? An example of this approach can be found here https://github.com/davemcg/eyeIntegration_app

**Comment by drewvoigt10** [comment]
Definitely! The RData files are freely hosted and available for download at: https://oculargeneexpression.org/pages/methods_tech.html
